name: Run test
on: push

jobs:
  # Label of the runner job
  runner-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_PASSWORD: postgres1
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5430:5432

    steps:
      - name: Set up Go 1.19.x
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
        id: go

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -cover ./...
